# ==============================================================================
# app/routers/auth.py — Authentication endpoints
# ==============================================================================
#
# ENDPOINTS:
#   POST /auth/signup   → create account, return tokens
#   POST /auth/login    → verify credentials, return tokens
#   POST /auth/refresh  → swap refresh token for new access token
#   POST /auth/logout   → revoke refresh token
#   GET  /auth/me       → return current user profile
#
# WHAT IS A ROUTER?
#   In FastAPI, an APIRouter groups related endpoints together.
#   It's like a "mini-app" for a specific feature (auth, users, etc.).
#   The router is "mounted" onto the main app in main.py with a prefix.
#
# DEPENDENCY INJECTION PATTERN:
#   Each route receives `db: AsyncSession = Depends(get_db)`.
#   FastAPI automatically calls `get_db()`, gets the session, passes it in,
#   and closes it after the route finishes. You never call `get_db()` manually.
# ==============================================================================

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.jwt import (
    create_access_token,
    create_refresh_token,
    hash_refresh_token,
)
from app.core.password import hash_password, verify_password
from app.core.rbac import get_current_user
from app.db.session import get_db
from app.models.user import Session as DBSession
from app.models.user import User, UserRole
from app.schemas.auth import (
    AuthResponse,
    LoginRequest,
    MessageResponse,
    RefreshRequest,
    SignupRequest,
    TokenResponse,
    UserResponse,
)

# Create the router. All routes defined here will be prefixed with "/auth"
# (that prefix is set in main.py when we do app.include_router(..., prefix="/auth")).
router = APIRouter(tags=["Authentication"])


# ==============================================================================
# POST /auth/signup
# ==============================================================================
@router.post(
    "/signup",
    response_model=AuthResponse,         # tells FastAPI what JSON shape to return
    status_code=status.HTTP_201_CREATED, # 201 = Created (more correct than 200 for new resources)
    summary="Create a new account",
)
async def signup(
    body: SignupRequest,          # FastAPI parses + validates the request body automatically
    request: Request,             # gives us access to HTTP headers (for IP address)
    db: AsyncSession = Depends(get_db),  # injected DB session
):
    """
    Create a new user account and workspace.

    1. Check email isn't already taken.
    2. Hash the password.
    3. Create the User row.
    4. Create a Session row (stores refresh token hash).
    5. Return access_token, refresh_token, and user profile.
    """
    # ── 1. Check for duplicate email ───────────────────────────────────────────
    existing = await db.execute(select(User).where(User.email == body.email))
    if existing.scalar_one_or_none():
        # 409 Conflict = resource already exists
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="An account with this email already exists.",
        )

    # ── 2. Create the user ────────────────────────────────────────────────────
    user = User(
        full_name=body.full_name,
        email=body.email,
        password_hash=hash_password(body.password),  # NEVER store plain password
        workspace_name=body.workspace_name,
        timezone=body.timezone,
        role=UserRole.ADMIN,   # first user in a workspace is always admin
    )
    db.add(user)
    # flush() sends the INSERT to the DB within the current transaction but
    # doesn't commit yet. This gives us user.id (generated by the DB) to use
    # when creating the session below.
    await db.flush()

    # ── 3. Generate tokens ────────────────────────────────────────────────────
    access_token, expires_in = create_access_token(user.id, user.role.value, user.email, user.workspace_name)
    raw_refresh, refresh_hash, refresh_expires = create_refresh_token()

    # ── 4. Create session ─────────────────────────────────────────────────────
    session = DBSession(
        user_id=user.id,
        refresh_token_hash=refresh_hash,
        ip_address=_get_client_ip(request),
        user_agent=request.headers.get("user-agent"),
        expires_at=refresh_expires,
    )
    db.add(session)

    # commit() finalizes both the User and Session inserts in one transaction.
    # If either fails, both are rolled back — data stays consistent.
    await db.commit()
    await db.refresh(user)   # reload user from DB (picks up server defaults like created_at)

    return AuthResponse(
        tokens=TokenResponse(
            access_token=access_token,
            refresh_token=raw_refresh,
            expires_in=expires_in,
        ),
        user=UserResponse.model_validate(user),
    )


# ==============================================================================
# POST /auth/login
# ==============================================================================
@router.post(
    "/login",
    response_model=AuthResponse,
    summary="Log in with email and password",
)
async def login(
    body: LoginRequest,
    request: Request,
    db: AsyncSession = Depends(get_db),
):
    """
    Authenticate with email + password.

    Security note: we return the SAME error message whether the email doesn't
    exist OR the password is wrong. This prevents "email enumeration" attacks
    where an attacker could learn which emails are registered.
    """
    # Generic error — same message for "no such user" AND "wrong password".
    bad_credentials = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid email or password.",
        headers={"WWW-Authenticate": "Bearer"},
    )

    # ── 1. Find the user ──────────────────────────────────────────────────────
    result = await db.execute(select(User).where(User.email == body.email))
    user = result.scalar_one_or_none()

    # Return the same error whether the user doesn't exist or password is wrong.
    if not user or not verify_password(body.password, user.password_hash):
        raise bad_credentials

    # ── 2. Check account is active ────────────────────────────────────────────
    if not user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="This account has been deactivated.",
        )

    # ── 3. Generate tokens + create session ───────────────────────────────────
    access_token, expires_in = create_access_token(user.id, user.role.value, user.email, user.workspace_name)
    raw_refresh, refresh_hash, refresh_expires = create_refresh_token()

    session = DBSession(
        user_id=user.id,
        refresh_token_hash=refresh_hash,
        ip_address=_get_client_ip(request),
        user_agent=request.headers.get("user-agent"),
        expires_at=refresh_expires,
    )
    db.add(session)
    await db.commit()

    return AuthResponse(
        tokens=TokenResponse(
            access_token=access_token,
            refresh_token=raw_refresh,
            expires_in=expires_in,
        ),
        user=UserResponse.model_validate(user),
    )


# ==============================================================================
# POST /auth/refresh
# ==============================================================================
@router.post(
    "/refresh",
    response_model=TokenResponse,
    summary="Get a new access token using a refresh token",
)
async def refresh_token(
    body: RefreshRequest,
    db: AsyncSession = Depends(get_db),
):
    """
    Exchange a valid refresh token for a new access token.

    Flow:
      1. Hash the incoming refresh token.
      2. Find the matching session in DB.
      3. Validate it's not revoked or expired.
      4. Issue a new access token (refresh token stays the same).
    """
    invalid_token = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Refresh token is invalid or expired.",
    )

    # Hash the incoming token and look it up in the sessions table.
    token_hash = hash_refresh_token(body.refresh_token)
    result = await db.execute(
        select(DBSession).where(DBSession.refresh_token_hash == token_hash)
    )
    session = result.scalar_one_or_none()

    if not session or not session.is_valid:
        raise invalid_token

    # Load the user to get their current role (role may have changed since login).
    result = await db.execute(select(User).where(User.id == session.user_id))
    user = result.scalar_one_or_none()

    if not user or not user.is_active:
        raise invalid_token

    # Issue a fresh access token. The refresh token stays unchanged.
    access_token, expires_in = create_access_token(user.id, user.role.value, user.email, user.workspace_name)

    return TokenResponse(
        access_token=access_token,
        refresh_token=body.refresh_token,  # return the same refresh token
        expires_in=expires_in,
    )


# ==============================================================================
# POST /auth/logout
# ==============================================================================
@router.post(
    "/logout",
    response_model=MessageResponse,
    summary="Revoke the current session's refresh token",
)
async def logout(
    body: RefreshRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """
    Revoke a refresh token (log out from one device).

    We look up the session by the refresh token hash, verify it belongs to the
    current user (security check!), then mark it revoked.
    """
    token_hash = hash_refresh_token(body.refresh_token)
    result = await db.execute(
        select(DBSession).where(
            DBSession.refresh_token_hash == token_hash,
            DBSession.user_id == current_user.id,  # ensure users can only revoke their own sessions
        )
    )
    session = result.scalar_one_or_none()

    if session and session.revoked_at is None:
        session.revoked_at = datetime.now(timezone.utc)
        await db.commit()

    # Return success even if the session wasn't found — avoids leaking info.
    return MessageResponse(message="Logged out successfully.")


# ==============================================================================
# GET /auth/me
# ==============================================================================
@router.get(
    "/me",
    response_model=UserResponse,
    summary="Get current user's profile",
)
async def get_me(
    current_user: User = Depends(get_current_user),
):
    """
    Return the authenticated user's profile.
    No DB query needed — get_current_user already loaded the User object.
    """
    return UserResponse.model_validate(current_user)


# ── Helper ─────────────────────────────────────────────────────────────────────

def _get_client_ip(request: Request) -> str | None:
    """
    Extract the real client IP from the request.
    When behind a reverse proxy (nginx, API Gateway), the real IP is in the
    X-Forwarded-For header, not request.client.host.
    """
    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        # X-Forwarded-For can be a comma-separated list: "client, proxy1, proxy2"
        # The leftmost IP is the original client.
        return forwarded_for.split(",")[0].strip()
    return request.client.host if request.client else None
